import type { Book } from "@/types/book";

export const booksSeed: Book[] = [
  {
    id: "1",
    title: "Anna Kariênina",
    author: "Liev Tolstói",
    year: 1877,
    genre: "Literatura Brasileira", // só pra preencher, pode trocar depois
    pages: 864,
    rating: 5,
    status: "LIDO",
    synopsis: "Um dos maiores clássicos da literatura mundial, explorando amor e sociedade.",
    cover: "/covers/annak.png",
  },
  {
    id: "2",
    title: "Harry Potter e o Cálice de Fogo",
    author: "J.K. Rowling",
    year: 2000,
    genre: "Fantasia",
    pages: 636,
    rating: 5,
    status: "LIDO",
    synopsis: "O Torneio Tribruxo coloca Harry diante de novos perigos e segredos.",
    cover: "/covers/hp4.png",
  },
  {
    id: "3",
    title: "Sapiens: Uma Breve História da Humanidade",
    author: "Yuval Noah Harari",
    year: 2011,
    genre: "História",
    pages: 443,
    rating: 4,
    status: "LENDO",
    synopsis: "Uma análise da evolução humana, da pré-história à era moderna.",
    cover: "/covers/sapiens.png",
  },
  {
    id: "4",
    title: "O Senhor dos Anéis: A Sociedade do Anel",
    author: "J.R.R. Tolkien",
    year: 1954,
    genre: "Fantasia",
    pages: 423,
    rating: 5,
    status: "QUERO_LER",
    synopsis: "A primeira parte da jornada épica para destruir o Um Anel.",
    cover: "/covers/lodr1.png",
  },
  {
    id: "5",
    title: "O Hobbit",
    author: "J.R.R. Tolkien",
    year: 1937,
    genre: "Fantasia",
    pages: 310,
    rating: 5,
    status: "LIDO",
    synopsis: "A aventura de Bilbo Bolseiro até a Montanha Solitária.",
    cover: "/covers/ohobbit.png",
  },
];
